# Generated by Django 3.0.5 on 2020-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200623_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
