# Generated by Django 3.0.5 on 2020-07-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20200706_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
