# Generated by Django 3.0.5 on 2020-07-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20200712_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
    ]
