# Generated by Django 3.0.5 on 2020-07-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_ticket_ticket_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
