# Generated by Django 3.0.5 on 2020-07-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_ticket_is_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='is_show',
            field=models.BooleanField(default=True),
        ),
    ]
