# Generated by Django 3.0.5 on 2020-05-14 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='description',
            new_name='bookScheduleDescription',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='end_date',
            new_name='bookScheduleEndDate',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='start_date',
            new_name='bookScheduleStartDate',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='title',
            new_name='bookScheduleTeam',
        ),
    ]
