# Generated by Django 3.0.5 on 2020-05-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20200427_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
    ]
